# -*- coding: utf-8 -*-
"""
Global configuration for nessai.
"""
import numpy as np

# Settings for live points
LOGL_DTYPE = 'f8'
IT_DTYPE = 'i4'
DEFAULT_FLOAT_DTYPE = 'f8'
DEFAULT_FLOAT_VALUE = np.nan
CORE_PARAMETERS = ['logP', 'logL', 'it']
CORE_PARAMETERS_DEFAULTS = [np.nan, np.nan, 0]
CORE_PARAMETERS_DTYPE = [DEFAULT_FLOAT_DTYPE, LOGL_DTYPE, IT_DTYPE]
EXTRA_PARAMETERS = []
EXTRA_PARAMETERS_DEFAULTS = []
EXTRA_PARAMETERS_DTYPE = []
NON_SAMPLING_PARAMETERS = CORE_PARAMETERS + EXTRA_PARAMETERS
NON_SAMPLING_DEFAULTS = CORE_PARAMETERS_DEFAULTS + EXTRA_PARAMETERS_DEFAULTS
NON_SAMPLING_DEFAULT_DTYPE = CORE_PARAMETERS_DTYPE + EXTRA_PARAMETERS_DTYPE
