name: Unit tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Unit tests - ${{ matrix.environment }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        environment: [py39, py310, py311, py312, py313]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v6
      with:
        # Pixi needs the setuptools-scm version when resolving downstream packages.
        fetch-depth: 0
    - uses: prefix-dev/setup-pixi@v0.10.0
      with:
        pixi-version: v0.78.0
        manifest-path: pyproject.toml
        environments: ${{ matrix.environment }}
    - name: Test with pytest
      run: |
        pixi run --locked -e ${{ matrix.environment }} test --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
